name: "Create vCluster Platform vCluster"
description: "GitHub Action to create a vCluster Platform-managed vCluster"
author: loft.sh
inputs:
  name:
    required: true
    description: "The name of the virtual cluster to create"
  account:
    required: false
    description: The cluster account to create the virtual cluster with if it doesn't exist
  cluster:
    required: false
    description: "The cluster to create the virtual cluster in"
  project:
    required: false
    description: "The project to use"
  space:
    required: false
    description: "The space to create the virtual cluster in"
  delete-after:
    required: false
    description: "If set to non zero, will tell vCluster Platform to delete the space after specified seconds of inactivity"
  sleep-after:
    required: false
    description: "If set to non zero, will tell the space to sleep after specified seconds of inactivity"
  disable-direct-cluster-endpoint:
    required: false
    description: "When enabled does not use an available direct cluster endpoint to connect to the vcluster"
  team:
    required: false
    description: "The team to create the virtual cluster for"
  user:
    required: false
    description: "The user to create the virtual cluster for"
  template:
    required: false
    description: "The virtual cluster template to use to create the virtual cluster"
  parameters:
    required: false
    description: "Embedded YAML array of App Parameters. The contents of this input will be written to a file and passed to the vcluster CLI"
  auto-cleanup:
    required: false
    description: "Delete the virtual cluster after the job run (default false)"
    default: "false"
  auto-cleanup-space:
    required: false
    description: "Delete the space after the job run (default to same value as auto-cleanup)"
  use:
    required: false
    description: "If vCluster Platform should use the virtual cluster if its already there"
    default: "false"
runs:
  using: "node20"
  main: "dist/main/index.js"
  post: "dist/post/index.js"
