name: build-test

on:
  pull_request:
  push:
    branches:
      - main
      - "releases/*"

permissions:
  pull-requests: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all
  vcluster_id:
    runs-on: ubuntu-latest
    steps:
      - id: vcluster_id
        run: echo "::set-output name=id::$RANDOM"
    outputs:
      vcluster_id: ${{ steps.vcluster_id.outputs.id }}
  # test-error-without-loft:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: ./
  #       continue-on-error: true
  #       with:
  #         name: create-mycluster-${{ matrix.os }}
  #     - run: loft list spaces
  test-auto-cleanup-default:
    needs:
      - vcluster_id
    strategy:
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: loft-sh/setup-loft@main
        with:
          version: v3.4.9
          url: ${{ secrets.LOFT_URL }}
          access-key: ${{ secrets.LOFT_ACCESS_KEY }}
      - uses: ./
        with:
          name: ${{ matrix.os }}-${{ needs.vcluster_id.outputs.vcluster_id }}
      - run: loft list vclusters
      - run: loft delete vcluster ${{ matrix.os }}-${{ needs.vcluster_id.outputs.vcluster_id }} --delete-space
  test-auto-cleanup-false:
    needs:
      - vcluster_id
      - test-auto-cleanup-default
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: loft-sh/setup-loft@main
        with:
          version: v3.4.9
          url: ${{ secrets.LOFT_URL }}
          access-key: ${{ secrets.LOFT_ACCESS_KEY }}
      - uses: ./
        with:
          name: cleanup-false-${{ needs.vcluster_id.outputs.vcluster_id }}
          auto-cleanup: false
      - run: loft list vclusters
      - run: loft delete vcluster cleanup-false-${{ needs.vcluster_id.outputs.vcluster_id }} --delete-space
  test-auto-cleanup-true:
    needs:
      - vcluster_id
      - test-auto-cleanup-false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: loft-sh/setup-loft@main
        with:
          version: v3.4.9
          url: ${{ secrets.LOFT_URL }}
          access-key: ${{ secrets.LOFT_ACCESS_KEY }}
      - uses: ./
        with:
          name: cleanup-true-${{ needs.vcluster_id.outputs.vcluster_id }}
          auto-cleanup: true
      - run: loft list vclusters
  test-manual-cleanup-space-warning:
    needs:
      - vcluster_id
      - test-auto-cleanup-true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: loft-sh/setup-loft@main
        with:
          version: v3.4.9
          url: ${{ secrets.LOFT_URL }}
          access-key: ${{ secrets.LOFT_ACCESS_KEY }}
      - uses: ./
        with:
          name: cleanup-warning-${{ needs.vcluster_id.outputs.vcluster_id }}
          auto-cleanup: false
          auto-cleanup-space: true
      - run: loft list vclusters
      - run: loft delete vcluster cleanup-warning-${{ needs.vcluster_id.outputs.vcluster_id }} --delete-space
  test-space:
    needs:
      - vcluster_id
      - test-manual-cleanup-space-warning
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: loft-sh/setup-loft@main
        with:
          version: v3.4.9
          url: ${{ secrets.LOFT_URL }}
          access-key: ${{ secrets.LOFT_ACCESS_KEY }}
      - uses: ./
        with:
          name: vcluster-space-${{ needs.vcluster_id.outputs.vcluster_id }}
          space: space-${{ needs.vcluster_id.outputs.vcluster_id }}
      - run: loft list vclusters
      - run: loft delete vcluster vcluster-space-${{ needs.vcluster_id.outputs.vcluster_id }} --delete-space
  test-delete-after:
    needs:
      - vcluster_id
      - test-space
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: loft-sh/setup-loft@main
        with:
          version: v3.4.9
          url: ${{ secrets.LOFT_URL }}
          access-key: ${{ secrets.LOFT_ACCESS_KEY }}
      - uses: ./
        with:
          name: delete-after-${{ needs.vcluster_id.outputs.vcluster_id }}
          delete-after: 60
      - run: loft list vclusters
      - run: loft delete vcluster delete-after-${{ needs.vcluster_id.outputs.vcluster_id }} --delete-space
  test-sleep-after:
    needs:
      - vcluster_id
      - test-delete-after
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: loft-sh/setup-loft@main
        with:
          version: v3.4.9
          url: ${{ secrets.LOFT_URL }}
          access-key: ${{ secrets.LOFT_ACCESS_KEY }}
      - uses: ./
        with:
          name: sleep-after-${{ needs.vcluster_id.outputs.vcluster_id }}
          sleep-after: 60
      - run: loft list vclusters
      - run: loft delete vcluster sleep-after-${{ needs.vcluster_id.outputs.vcluster_id }} --delete-space
  test-disable-direct-cluster-endpoint:
    needs:
      - vcluster_id
      - test-sleep-after
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: loft-sh/setup-loft@main
        with:
          version: v3.4.9
          url: ${{ secrets.LOFT_URL }}
          access-key: ${{ secrets.LOFT_ACCESS_KEY }}
      - uses: ./
        with:
          name: disable-endpoint-${{ needs.vcluster_id.outputs.vcluster_id }}
          disable-direct-cluster-endpoint: true
      - run: loft list vclusters
      - run: loft delete vcluster disable-endpoint-${{ needs.vcluster_id.outputs.vcluster_id }} --delete-space
  test-template:
    needs:
      - vcluster_id
      - test-disable-direct-cluster-endpoint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: loft-sh/setup-loft@main
        with:
          version: v3.4.9
          url: ${{ secrets.LOFT_URL }}
          access-key: ${{ secrets.LOFT_ACCESS_KEY }}
      - uses: ./
        with:
          name: template-${{ needs.vcluster_id.outputs.vcluster_id }}
          template: example-template
          user: russellcentanni
          parameters: |
            apps:
            - name: example-manifests
              parameters:
                password: '${{ needs.vcluster_id.outputs.vcluster_id }}'
                version: '8.0'
      - run: loft list vclusters
      - run: loft delete vcluster template-${{ needs.vcluster_id.outputs.vcluster_id }} --delete-space
